### ISSUE TITLE
Problem with shared libs compiling or linking on Mac OS (OSX)

### ISSUE THREAD

**Issue by dsavenko** [ctuning/ck-autotuning#17]
Hi,

Looks like there is a problem with compiling or linking shared libs while doing `ck run program` on OSX. I do compile and get this:

```
$ ck compile program:cbench-automotive-susan

***************************************************************************************
Current directory: /Users/dsavenko/CK/ctuning-programs/program/cbench-automotive-susan/tmp
***************************************************************************************

Resolving software dependencies ...

*** Dependency 1 = compiler (C compiler):

    Resolved. CK environment UID = 2a0247258e6fae60 (detected version 3.8.0)

*** Dependency 2 = xopenme (xOpenME library):

    Resolved. CK environment UID = 0dc79501048b7bb2

***************************************************************************************
Detected compiler version: 3.8.0

***************************************************************************************
Compiler vars:
  XOPENME=
***************************************************************************************

Executing prepared batch file tmp-5qVXpo.sh ...

clang -c   -I../ -DXOPENME -I/Users/dsavenko/si/checker/include -I/Users/dsavenko/CK-TOOLS/lib-rtl-xopenme-0.3-llvm-3.8.0-macos-64/include  ../susan.c  -o susan.o
../susan.c:688:9: warning: implicit conversion from 'double' to 'TOTAL_TYPE' (aka 'int') changes value from 0.1 to 0 [-Wliteral-conversion]
  total=0.1; /* test for total's type */
       ~^~~
1 warning generated.
clang    susan.o  -o a.out    -L/Users/dsavenko/CK-TOOLS/lib-rtl-xopenme-0.3-llvm-3.8.0-macos-64/lib -lrtlxopenme -lm
***************************************************************************************
Compilation time: 0.201 sec.; Object size: 47244; MD5: 
```

(**Note** there's no MD5 hash which is unusual)

Then, I do run:

```
$ ck run program:cbench-automotive-susan


OS CK UOA:            macos-64 (fb7d7f63b44b9ea3)

OS name:              Mac OS X 10.11.6
Short OS name:        Darwin 15.6.0
Long OS name:         Darwin-15.6.0-x86_64-i386-64bit
OS bits:              64

Platform init UOA:    42818da3a0789331
***************************************************************************************
Current directory: /Users/dsavenko/CK/ctuning-programs/program/cbench-automotive-susan/tmp

Reloading depedencies from compilation tmp-deps.json ...
***************************************************************************************

Resolving software dependencies ...

*** Dependency 1 = compiler (C compiler):

    Resolved. CK environment UID = 2a0247258e6fae60 (detected version 3.8.0)

*** Dependency 2 = xopenme (xOpenME library):

    Resolved. CK environment UID = 0dc79501048b7bb2


More than one commmand line is found to run this program:

0) corners ($#BIN_FILE#$ $#dataset_path#$$#dataset_filename#$ tmp-output.tmp -c)
1) edges ($#BIN_FILE#$ $#dataset_path#$$#dataset_filename#$ tmp-output.tmp -e)
2) smoothing ($#BIN_FILE#$ $#dataset_path#$$#dataset_filename#$ tmp-output.tmp -s)

Select command line (or Enter to select 0): 

More than one dataset entry is found for this program:

0) image-pgm-0001 (b2130844c38e4a56)
1) image-pgm-clean-gray-square-600-450-8 (c5a378cde441bbb7)
2) image-pgm-from-pamela-100 (d11ad4b49f2b9f45)

Select dataset UOA (or Enter to select 0): 
  Cleaning output files and directories:
    tmp-output1.tmp
    tmp-output2.tmp
    tmp-output.tmp
    tmp-ck-timer.json

***************************************************************************************
### Calibration 1 out of 10 ; Kernel repeat number = 1
***************************************************************************************
***************************************************************************************
Prepared script:

#! /bin/bash


export PATH=/Users/dsavenko/CK/ck-env/platform.init/generic-linux:$PATH


. /Users/dsavenko/CK/local/env/2a0247258e6fae60/env.sh
. /Users/dsavenko/CK/local/env/0dc79501048b7bb2/env.sh

. /Users/dsavenko/CK/local/env/2a0247258e6fae60/env.sh 1

export CT_REPEAT_MAIN=1


export CK_DATASET_PATH=/Users/dsavenko/CK/ctuning-datasets-min/dataset/image-pgm-0001/

export CK_DATASET_FILENAME=data.pgm

echo    executing code ...
 ./a.out /Users/dsavenko/CK/ctuning-datasets-min/dataset/image-pgm-0001/data.pgm tmp-output.tmp -c > tmp-output1.tmp 2> tmp-output2.tmp

***************************************************************************************
  (bash -c "chmod 755 ./tmp-i7Rhe2.sh; . ./tmp-i7Rhe2.sh")

  (sleep 0.5 sec ...)

  (run ...)
executing code ...
./tmp-i7Rhe2.sh: line 20: 20215 Trace/BPT trap: 5       ./a.out /Users/dsavenko/CK/ctuning-datasets-min/dataset/image-pgm-0001/data.pgm tmp-output.tmp -c > tmp-output1.tmp 2> tmp-output2.tmp

  (reading fine grain timers from tmp-ck-timer.json ...)


Program execution likely failed (can't find fine grain timers)!
```

Stderr (the `tmp-output2.tmp` file) contains this:

```
dyld: Library not loaded: librtlxopenme.so
  Referenced from: /Users/dsavenko/CK/ctuning-programs/program/cbench-automotive-susan/tmp/./a.out
  Reason: image not found
```

The problem reproduces for each program with shared dependencies. 

I suspect the library either compiled improperly (e.g. this is no .dylib file), or there may be a problem with linking.

**Comment by gfursin** [comment]
Hmmm, I don't use XOS, so couldn't really check, but if I am correct, you managed to run ck crowdtuning on MacOS, and it worked fine in the past (and most my benchmarks use XOpenME) ...
Maybe something changed in LLVM CK description and it doesn't produce correct dynamic libs.

Another reason is that I use LD_LIBRARY_PATH to find this dynamic lib. I think it may be something else on MacOS?

Do you mind to find and copy librtlxopenme.so (somewhere in /Users/dsavenko/CK-TOOLS) manually to /Users/dsavenko/CK/ctuning-programs/program/cbench-automotive-susan/tmp and then try again?

Thanks!

**Comment by dsavenko** [comment]
Yeah, I find this strange, too. 

If I copy `librtlxopenme.so` as you suggested, it works as expected. If I manually set LD_LIBRARY_PATH to `/Users/dsavenko/CK-TOOLS/lib-rtl-xopenme-0.3-llvm-3.8.0-macos-64/lib`, it **doesn't** work.

Looks like on Mac you need to specify `DYLD_LIBRARY_PATH` (or, better, `DYLD_FALLBACK_LIBRARY_PATH`, as explained here: http://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s ) instead of LD_LIBRARY_PATH . 

If I specify either of the DYLD_* vars and run `./a.out` manually, it works.

**Comment by dsavenko** [comment]
I guess, I can provide a PR to fix this for Mac. Give me some time for this :)

**Comment by dsavenko** [comment]
OK, I fixed this issue by editing `ck-env/soft/lib.rtl.xopenme/customize.py`. LD_LIBRARY_PATH  is hardcoded there. I just did so that the var's name's taken from the `host_os_dict` input var. 

But there are a lot of hardcoded cases of `LD_LIBRARY_PATH` in other customize scripts. I can fix all of them, but it looks like we'd better devise some general way for soft to contribute to dynamic lib path in order to eliminate such mistakes in the future. 

Please, share your thoughts.

**Comment by gfursin** [comment]
Yeap, that was the right way to fix. The idea in the CK is to let users quickly convert their ad-hoc scripts to CK format (to quickly prototype research ideas) and then gradually convert them to canonical way. So, I quickly hardwired LD_LIBRARY_PATH, but later we found that MacOS has different env and we added this meta in os:macos-64. Then the idea is to gradually convert various soft entries to use host_os_dict ...

In a longer term, I think that we can make it even better by specifying all such paths (dyn lib, stat lib, bin, include) via meta rather than scripts, but we are not there yet and it's a longer term plan.

So, if you can fix that (by the way, do you mind to fix at least soft:lib.rtl.milepost.codelet & soft:lib.rtl.polybench to be able to run crowd-tuning on MacOS), that would be great! Just send me a pull request! Thanks a lot!!!

**Comment by dsavenko** [comment]
Done. See https://github.com/ctuning/ck-env/pull/17

The approach may be used in other soft descriptions as well (there are a lot of LD_LIBRARY_PATH usage there). The PR only fixes the three you mentioned, but I can change the other as well. Would you like me to do so?

**Comment by gfursin** [comment]
Cool! Thanks! If it's not very complex, please update other soft entries too... It would be useful to make CK workflows run on MacOS ... Thanks a lot!

**Comment by dsavenko** [comment]
Updated other soft entries: https://github.com/ctuning/ck-env/pull/18
