### ISSUE TITLE
Add --valgring option to run program under valgring

### ISSUE THREAD

**Issue by DVEfremov** [ctuning/ck-autotuning#26]
It requires mostly then we getting "Segmentation fault" error for some programs.
Work around if 
```
$ ck run program:caffe-time  --keep 
$ ./tmp-PrUGAu.sh #or some other generated file name 
$  valgrind fully_connected
```
it will be much better to have option and run it it one ck command 
```
$ ck run program:caffe-time  --valgrind
```
For this need to add valgrind as package and soft 
and pass ENV CK_ENV_VALGRIND_TOOL  at env.sh 

Then also valgrind could be compiled and run under android.

**Comment by gfursin** [comment]
I added support for valgrind for Linux. You need to update all repos to try it.

I added ck-env:soft:lib.valgrind entry to detect installed valgrind (for now Linux) and then added flag --valgrind to ck pipeline program (NOTE it's a pipeline, not compile/run), i.e. to test it do the following:
$ ck pipeline program:cbench-automotive-susan --valgrind 

Please tell me if it works and if you need some other enhancements ...

**Comment by DVEfremov** [comment]
I've tried - works fine. Thanks!
