### ISSUE TITLE
target not passed to platform.gpgpu detect in program/module

### ISSUE THREAD

**Issue by sztaylor** [ctuning/ck-autotuning#30]
Hi all,

I am using the machine update_target_os_dict parameter to override some target_os parameters. Unfortunately program/module.py was not passing the target when calling platform.gpgpu detect which meant that the update_target_os_dict overrides were not available. This is only an issue for programs which use the need_compute_device flag. The detect action does accept a target parameter so I've provided a patch which provides it to the action if not empty. 

Note: I have only tested this when passing a target to the pipeline.

Let me know if you require more information for testing etc.
[platform_gpgpu_detect_with_target.patch.txt](https://github.com/ctuning/ck-autotuning/files/2118344/platform_gpgpu_detect_with_target.patch.txt)

Regards,
Stuart

**Comment by gfursin** [comment]
Thanks for reporting! I will check it shortly ...

**Comment by gfursin** [comment]
Hi Stuart,
I checked your patch and it's ok - I indeed forgot to pass "target" to GPGPU module.
I merged it.
Thanks for reporting and feel free to give us a shout if you have other suggestions or issues,
Grigori
