### ISSUE TITLE
failed tests

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-autotuning#31]
Hi @ens-lg4. I just noticed that tests fail on this repo - is it possible to check what is happening, please? Thanks a lot!

**Comment by ens-lg4** [comment]
Fixed the OSX side of it (Travis recently made a few changes on their side, so we'll have to gradually mirror them on the receiving side).

Will have a look into Appveyor tomorrow - it is a totally separate issue.

**Comment by ens-lg4** [comment]
Fixed.
Appveyor's installation of the new MS compiler v19.15 was broken.
After switching to v.19.00 the test worked again.
